# -*- mode: ruby -*-
# vi: set ft=ruby :

#
#	Ubuntu Xenial 64-bit Linux mit Docker
#

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"
  
    # This section allows the user to communicate with the vagrant machine over commonly used ports like http
    config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    config.vm.network "forwarded_port", guest:8081, host:8081, auto_correct: true
    config.vm.network "forwarded_port", guest:8082, host:8082, auto_correct: true
    config.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: true  
    for i in 32760..32780
      config.vm.network :forwarded_port, guest: i, host: i
    end
      
    # Create a private network
    config.vm.hostname = "docker"
    config.vm.network "private_network", ip:"192.168.60.101"
    
    config.vm.provision "shell",
      inline: "mkdir /home/vagrant/shared_folder; true"

    #Sync shared folder
    config.vm.synced_folder "shared_folder/", "/home/vagrant/shared_folder"
  
    config.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
    end
  
    # Docker Provisioner
    config.vm.provision "docker" do |d|
      d.pull_images "mysql:8.0.16"
      d.pull_images "ghost:2.25.1-alpine"
      d.run "ghost_mysql", image: "mysql:8.0.16", args: "-e MYSQL_ROOT_PASSWORD=admin -e MYSQL_USER=ghost -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=ghost --restart=always"
      d.run "ghost", image: "ghost:2.25.1-alpine", args: "--link ghost_mysql:mysql -e database__client=mysql -e database__connection__host=ghost_mysql -e database__connection__user=ghost -e database__connection__password=secret -e database__connection__database=ghost -p 2368:2368 --restart=always"     
    end
end
